#!/bin/sh

# create all the symlinks to /bin/busybox
/bin/busybox --install -s

# mount things needed by this script
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

root="/dev/mmcblk0"

mount "$root" /newroot
mount proc /newroot/proc -t proc
chroot /newroot /stage2.sh
rm /newroot/stage2.sh
umount /newroot

reboot -f
